### ISSUE TITLE
community site is missing a link to this repo

### ISSUE THREAD

**Issue by nevir** [phlipper/chef-newrelic-sysmond#3]
http://community.opscode.com/cookbooks/newrelic-sysmond

**Comment by phlipper** [comment]
@nevir what do you mean by this? Are you suggesting an update to the README?

**Comment by phlipper** [comment]
Closing due to lack of response.

**Comment by jalessio** [comment]
@phlipper @nevir means that the "Homepage" field is missing on the Opscode Community site @ http://community.opscode.com/cookbooks/newrelic-sysmond

![screen shot 2013-09-17 at 12 18 08 pm](https://f.cloud.github.com/assets/178680/1159874/fb078d20-1fcd-11e3-9e1d-239a37228ce1.png)

See http://community.opscode.com/cookbooks/build-essential for an example of "Homepage" field linking to the github repo for the cookbook.

![screen shot 2013-09-17 at 12 17 57 pm](https://f.cloud.github.com/assets/178680/1159875/ffd4cc64-1fcd-11e3-84ee-63995a6ccd45.png)

In order to find the source for chef-newrelic-sysmond I ended up googling your name plus the cookbook name which led me to the github repo page. I assume this is a field you set when registering the cookbook with the Opscode Community site.

**Comment by phlipper** [comment]
@nevir, @jalessio, thank you for the information. I have updated the community site with a link to this repo.
